apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../headless

# All the resources that make up the deployment
resources:
# global resources
- ../../admindeployment/clustersync
- ../../console

# configMapGenerator:
# TODO Nebula Console Configuration
#- name: nebula-console-config
#  files:
#    - ./config/console.yaml
