database:
  port: 5432
  username: nebula
  # TODO Change this to match aurora or rds postgres endpoint
  host: nebulaadmin-cluster.cluster-456123e6ivib.us-west-2.rds.amazonaws.com
  dbname: nebula
  passwordPath: /etc/db/pass.txt
