{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nebula-pod-webhook.name" . }}
  namespace: {{ template "nebula.namespace" . }}
  {{- with .Values.webhook.service.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: ExternalName
  externalName: host.docker.internal
{{- end }}
