{{- if .Values.nebulapropeller.enabled }}
---
{{- if .Values.nebulapropeller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nebulapropeller.name" . }}
  namespace: {{ template "nebula.namespace" . }}
  labels: {{ include "nebulapropeller.labels" . | nindent 4 }}
  {{- with .Values.nebulapropeller.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end}}
{{- with .Values.nebulapropeller.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if $.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRole
metadata:
  name: {{ template "nebula.namespace" . -}}-{{- template "nebulapropeller.name" . }}
  labels: {{ include "nebulapropeller.labels" . | nindent 4 }}
rules:
# Allow RO access to PODS
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# Allow Event recording access
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - delete
  - patch
# Allow Access All plugin objects
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
# Allow Access to CRD
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
# Allow Access to all resources under nebula.lyft.com
- apiGroups:
  - nebula.lyft.com
  resources:
  - nebulaworkflows
  - nebulaworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
  - post
  - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "nebula.namespace" . -}}-{{- template "nebulapropeller.name" . }}
  labels: {{ include "nebulapropeller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nebula.namespace" . -}}-{{- template "nebulapropeller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "nebulapropeller.name" . }}
  namespace: {{ template "nebula.namespace" . }}
{{- end }}
