// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	admin "github.com/nebulaclouds/nebula/nebulaidl/gen/pb-go/nebulaidl/admin"

	core "github.com/nebulaclouds/nebula/nebulaidl/gen/pb-go/nebulaidl/core"

	launchplan "github.com/nebulaclouds/nebula/nebulapropeller/pkg/controller/nodes/subworkflow/launchplan"

	mock "github.com/stretchr/testify/mock"
)

// NebulaAdmin is an autogenerated mock type for the NebulaAdmin type
type NebulaAdmin struct {
	mock.Mock
}

type NebulaAdmin_GetLaunchPlan struct {
	*mock.Call
}

func (_m NebulaAdmin_GetLaunchPlan) Return(_a0 *admin.LaunchPlan, _a1 error) *NebulaAdmin_GetLaunchPlan {
	return &NebulaAdmin_GetLaunchPlan{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *NebulaAdmin) OnGetLaunchPlan(ctx context.Context, launchPlanRef *core.Identifier) *NebulaAdmin_GetLaunchPlan {
	c_call := _m.On("GetLaunchPlan", ctx, launchPlanRef)
	return &NebulaAdmin_GetLaunchPlan{Call: c_call}
}

func (_m *NebulaAdmin) OnGetLaunchPlanMatch(matchers ...interface{}) *NebulaAdmin_GetLaunchPlan {
	c_call := _m.On("GetLaunchPlan", matchers...)
	return &NebulaAdmin_GetLaunchPlan{Call: c_call}
}

// GetLaunchPlan provides a mock function with given fields: ctx, launchPlanRef
func (_m *NebulaAdmin) GetLaunchPlan(ctx context.Context, launchPlanRef *core.Identifier) (*admin.LaunchPlan, error) {
	ret := _m.Called(ctx, launchPlanRef)

	var r0 *admin.LaunchPlan
	if rf, ok := ret.Get(0).(func(context.Context, *core.Identifier) *admin.LaunchPlan); ok {
		r0 = rf(ctx, launchPlanRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.LaunchPlan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *core.Identifier) error); ok {
		r1 = rf(ctx, launchPlanRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NebulaAdmin_GetStatus struct {
	*mock.Call
}

func (_m NebulaAdmin_GetStatus) Return(_a0 *admin.ExecutionClosure, _a1 *core.LiteralMap, _a2 error) *NebulaAdmin_GetStatus {
	return &NebulaAdmin_GetStatus{Call: _m.Call.Return(_a0, _a1, _a2)}
}

func (_m *NebulaAdmin) OnGetStatus(ctx context.Context, executionID *core.WorkflowExecutionIdentifier) *NebulaAdmin_GetStatus {
	c_call := _m.On("GetStatus", ctx, executionID)
	return &NebulaAdmin_GetStatus{Call: c_call}
}

func (_m *NebulaAdmin) OnGetStatusMatch(matchers ...interface{}) *NebulaAdmin_GetStatus {
	c_call := _m.On("GetStatus", matchers...)
	return &NebulaAdmin_GetStatus{Call: c_call}
}

// GetStatus provides a mock function with given fields: ctx, executionID
func (_m *NebulaAdmin) GetStatus(ctx context.Context, executionID *core.WorkflowExecutionIdentifier) (*admin.ExecutionClosure, *core.LiteralMap, error) {
	ret := _m.Called(ctx, executionID)

	var r0 *admin.ExecutionClosure
	if rf, ok := ret.Get(0).(func(context.Context, *core.WorkflowExecutionIdentifier) *admin.ExecutionClosure); ok {
		r0 = rf(ctx, executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ExecutionClosure)
		}
	}

	var r1 *core.LiteralMap
	if rf, ok := ret.Get(1).(func(context.Context, *core.WorkflowExecutionIdentifier) *core.LiteralMap); ok {
		r1 = rf(ctx, executionID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*core.LiteralMap)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *core.WorkflowExecutionIdentifier) error); ok {
		r2 = rf(ctx, executionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type NebulaAdmin_Initialize struct {
	*mock.Call
}

func (_m NebulaAdmin_Initialize) Return(_a0 error) *NebulaAdmin_Initialize {
	return &NebulaAdmin_Initialize{Call: _m.Call.Return(_a0)}
}

func (_m *NebulaAdmin) OnInitialize(ctx context.Context) *NebulaAdmin_Initialize {
	c_call := _m.On("Initialize", ctx)
	return &NebulaAdmin_Initialize{Call: c_call}
}

func (_m *NebulaAdmin) OnInitializeMatch(matchers ...interface{}) *NebulaAdmin_Initialize {
	c_call := _m.On("Initialize", matchers...)
	return &NebulaAdmin_Initialize{Call: c_call}
}

// Initialize provides a mock function with given fields: ctx
func (_m *NebulaAdmin) Initialize(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NebulaAdmin_Kill struct {
	*mock.Call
}

func (_m NebulaAdmin_Kill) Return(_a0 error) *NebulaAdmin_Kill {
	return &NebulaAdmin_Kill{Call: _m.Call.Return(_a0)}
}

func (_m *NebulaAdmin) OnKill(ctx context.Context, executionID *core.WorkflowExecutionIdentifier, reason string) *NebulaAdmin_Kill {
	c_call := _m.On("Kill", ctx, executionID, reason)
	return &NebulaAdmin_Kill{Call: c_call}
}

func (_m *NebulaAdmin) OnKillMatch(matchers ...interface{}) *NebulaAdmin_Kill {
	c_call := _m.On("Kill", matchers...)
	return &NebulaAdmin_Kill{Call: c_call}
}

// Kill provides a mock function with given fields: ctx, executionID, reason
func (_m *NebulaAdmin) Kill(ctx context.Context, executionID *core.WorkflowExecutionIdentifier, reason string) error {
	ret := _m.Called(ctx, executionID, reason)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.WorkflowExecutionIdentifier, string) error); ok {
		r0 = rf(ctx, executionID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NebulaAdmin_Launch struct {
	*mock.Call
}

func (_m NebulaAdmin_Launch) Return(_a0 error) *NebulaAdmin_Launch {
	return &NebulaAdmin_Launch{Call: _m.Call.Return(_a0)}
}

func (_m *NebulaAdmin) OnLaunch(ctx context.Context, launchCtx launchplan.LaunchContext, executionID *core.WorkflowExecutionIdentifier, launchPlanRef *core.Identifier, inputs *core.LiteralMap) *NebulaAdmin_Launch {
	c_call := _m.On("Launch", ctx, launchCtx, executionID, launchPlanRef, inputs)
	return &NebulaAdmin_Launch{Call: c_call}
}

func (_m *NebulaAdmin) OnLaunchMatch(matchers ...interface{}) *NebulaAdmin_Launch {
	c_call := _m.On("Launch", matchers...)
	return &NebulaAdmin_Launch{Call: c_call}
}

// Launch provides a mock function with given fields: ctx, launchCtx, executionID, launchPlanRef, inputs
func (_m *NebulaAdmin) Launch(ctx context.Context, launchCtx launchplan.LaunchContext, executionID *core.WorkflowExecutionIdentifier, launchPlanRef *core.Identifier, inputs *core.LiteralMap) error {
	ret := _m.Called(ctx, launchCtx, executionID, launchPlanRef, inputs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, launchplan.LaunchContext, *core.WorkflowExecutionIdentifier, *core.Identifier, *core.LiteralMap) error); ok {
		r0 = rf(ctx, launchCtx, executionID, launchPlanRef, inputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
