apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: nebulaworkflows.nebula.lyft.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: nebula.lyft.com
  # either Namespaced or Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nebulaworkflows
    # singular name to be used as an alias on the CLI and for display
    singular: nebulaworkflow
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: NebulaWorkflow
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - fly
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
