apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebulapropeller
  namespace: nebula
  annotations:
    # TODO the role to use
    eks.amazonaws.com/role-arn: "arn:aws:iam::111222333456:role/nebula-operator"
