# WARNING: THIS FILE IS MANAGED IN THE 'BOILERPLATE' REPO AND COPIED TO OTHER REPOSITORIES.
# ONLY EDIT THIS FILE FROM WITHIN THE 'LYFT/BOILERPLATE' REPOSITORY:
# 
# TO OPT OUT OF UPDATES, SEE https://github.com/lyft/boilerplate/blob/master/Readme.rst

FROM --platform=${BUILDPLATFORM} golang:1.19-alpine3.16 as builder

ARG TARGETARCH
ENV GOARCH "${TARGETARCH}"
ENV GOOS linux

RUN apk add git openssh-client make curl

WORKDIR /go/src/github.com/nebulaclouds/nebulacopilot

COPY datacatalog ../datacatalog
COPY nebulaadmin ../nebulaadmin
COPY nebulacopilot .
COPY nebulaidl ../nebulaidl
COPY nebulaplugins ../nebulaplugins
COPY nebulapropeller ../nebulapropeller
COPY nebulastdlib ../nebulastdlib

# This 'linux_compile' target should compile binaries to the /artifacts directory
# The main entrypoint should be compiled to /artifacts/nebulaplugins
RUN make linux_compile

# update the PATH to include the /artifacts directory
ENV PATH="/artifacts:${PATH}"

# This will eventually move to centurylink/ca-certs:latest for minimum possible image size
FROM alpine:3.16
LABEL org.opencontainers.image.source https://github.com/lyft/nebulaplugins

COPY --from=builder /artifacts /bin

RUN apk --update add ca-certificates

CMD ["nebula-copilot"]
