name: monodocs-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - codespell
  - furo
  - nebulakit
  - gitpython
  - ipython!=8.7.0
  - graphviz
  - jupytext
  - myst-nb
  - psycopg2-binary
  - recommonmark
  - sphinx==4.5.0
  - sphinx-prompt
  - sphinx-click
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-issues
  - sphinx_fontawesome
  - sphinx-panels
  - sphinxcontrib-mermaid
  - sphinxcontrib-youtube==1.2.0
  - sphinx-tabs
  - sphinx-tags==0.2.1

  # Packages for Plugin docs
  # Package name                Plugin needing it
  - retry                       # aws sagemaker
  - botocore                    # fsspec
  - fsspec                      # fsspec
  - google-cloud-bigquery       # bigquery
  - markdown                    # deck
  - plotly                      # deck
  - great-expectations          # greatexpectations
  - datasets                    # huggingface
  - kubernetes                  # k8s-pod
  - modin                       # modin
  - pandera                     # pandera
  - pydantic                    # vaex, pydantic
  - papermill                   # papermill
  - jupyter                     # papermill
  - polars                      # polars
  - pyspark                     # spark
  - sqlalchemy                  # sqlalchemy
  - pytorch                     # pytorch
  - skl2onnx                    # onnxscikitlearn
  - numpy==1.23.5               # onnxtensorflow numpy.bool warning
  - tf2onnx                     # onnxtensorflow
  - tensorflow>=2.13.0          # onnxtensorflow
  - scikit-learn                # scikit-learn
  - dask[distributed]           # dask
  - mlflow==2.7.0               # mlflow
  - snowflake-connector-python  # snowflake
  - vaex-core                   # vaex

  - pip:
    - sphinx-code-include
    - sphinxext-remoteliteralinclude
    - sphinx_markdown_tables
    - sphinxcontrib-video
    - nebulakitplugins-deck-standard
    - nebulakitplugins-kfpytorch
    - nebulakitplugins-sqlalchemy
    - dolt_integrations
    - google-cloud
    - ydata_profiling
    - whylogs==1.3.3              # whylogs
    - whylabs-client              # whylogs
    - ray==2.6.3
    - duckdb

platforms:
  - linux-64
  - osx-arm64
