{{- if .Values.nebulaadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nebula-admin-secrets
  namespace: {{ template "nebula.namespace" . }}
type: Opaque
stringData:
{{- with .Values.nebulaadmin.secrets -}}
{{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
