// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NebulaWorkflowListerExpansion allows custom methods to be added to
// NebulaWorkflowLister.
type NebulaWorkflowListerExpansion interface{}

// NebulaWorkflowNamespaceListerExpansion allows custom methods to be added to
// NebulaWorkflowNamespaceLister.
type NebulaWorkflowNamespaceListerExpansion interface{}
