apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulapropeller
  namespace: nebula
spec:
  template:
    spec:
      containers:
      - name: nebulapropeller
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "1Gi"
