---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nebula
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          emptyDir: {}
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nebula
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
