{{- if .Values.nebulapropeller.enabled }}
{{- if .Values.nebulapropeller.createCRDs }}
{{- if $.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1/CustomResourceDefinition" }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: nebulaworkflows.nebula.lyft.com
spec:
  group: nebula.lyft.com
  names:
    kind: NebulaWorkflow
    plural: nebulaworkflows
    shortNames:
      - fly
    singular: nebulaworkflow
  scope: Namespaced
{{- if $.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1/CustomResourceDefinition" }}
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
{{- else }}
  version: v1alpha1
{{- end }}
{{- end }}
{{- end }}