apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nebula-sandbox.persistence.minioVolumeName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nebula-sandbox.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/nebula/storage/minio"
