apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nebula-sandbox.persistence.minioVolumeName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nebula-sandbox.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "nebula-sandbox.persistence.minioVolumeName" . }}
