# Service
apiVersion: v1
kind: Service
metadata:
  name: nebulaadmin
  namespace: nebula
  annotations:
    # This tells contour to use a H2 connection for the port associated
    # with the name 'grpc' under spec/ports.
    # For more information, refer to
    # https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-service-annotations
    # # Following this issue - the annotation was updated https://github.com/projectcontour/contour/issues/2092
    projectcontour.io/upstream-protocol.h2c: "grpc"
spec:
  selector:
    app: nebulaadmin
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8088
  - name: grpc
    protocol: TCP
    port: 81
    targetPort: 8089
