apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nebulaagent.name" . }}
  namespace: {{ template "nebula.namespace" . }}
type: Opaque
{{- with .Values.agentSecret.secretData -}}
{{ tpl (toYaml .) $ | nindent 0 }}
{{- end }}
