# ---------------------------------------------------------------------
# NEBULA_AGENT SETTINGS
# ---------------------------------------------------------------------

# nameOverride String to override nebulaagent.name template
nameOverride: ""
# fullnameOverride String to override nebulaagent.fullname template
fullnameOverride: ""
# commonLabels Add labels to all the deployed resources
commonLabels: {}
# commonAnnotations Add annotations to all the deployed resources
commonAnnotations: {}

agentSecret:
  # -- Specify your Secret (with sensitive data) or pseudo-manifest (without sensitive data).
  secretData:
    data:
      username: User

# -- Replicas count for nebulaagent deployment
replicaCount: 1
image:
  # -- Docker image for nebulaagent deployment
  repository: ghcr.io/nebulaclouds/nebulaagent
  # -- Docker image tag
  tag: 1.10.1 # NEBULAAGENT_TAG
  # -- Docker image pull policy
  pullPolicy: IfNotPresent
ports:
  containerPort: 8000
  name: agent-grpc
# -- Default resources requests and limits for nebulaagent deployment
resources:
  limits:
    cpu: 500m
    ephemeral-storage: 200Mi
    memory: 200Mi
  requests:
    cpu: 500m
    ephemeral-storage: 200Mi
    memory: 200Mi
# -- Default regex string for searching configuration files
configPath: /etc/nebulaagent/config/*.yaml
# -- Service settings for nebulaagent
service:
  annotations:
    projectcontour.io/upstream-protocol.h2c: grpc
  type: ClusterIP
# -- Configuration for service accounts for nebulaagent
serviceAccount:
  # -- Should a service account be created for nebulaagent
  create: true
  # -- Annotations for ServiceAccount attached to nebulaagent pods
  annotations: {}
  # -- ImagePullSecrets to automatically assign to the service account
  imagePullSecrets: []
# -- Annotations for nebulaagent pods
podAnnotations: {}
# -- nodeSelector for nebulaagent deployment
nodeSelector: {}
# -- tolerations for nebulaagent deployment
tolerations: []
# -- affinity for nebulaagent deployment
affinity: {}
# -- Appends additional volumes to the deployment spec. May include template values.
additionalVolumes: []
# -- Appends additional volume mounts to the main container's spec. May include template values.
additionalVolumeMounts: []
# -- Appends additional containers to the deployment spec. May include template values.
additionalContainers: []
# -- Appends extra command line arguments to the main command
extraArgs: {}
# -- Sets priorityClassName for datacatalog pod(s).
priorityClassName: ""
