apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
    # TODO add your security groups here
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-....,sg-...,sg-..."
    # TODO add your external dns here
    external-dns.alpha.kubernetes.io/hostname: "nebula.subdomain.mydomain.com"
  name: nebulaconsole
  namespace: nebula
spec:
  loadBalancerSourceRanges:
    # TODO limit source ranges if you want
    - 0.0.0.0
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nebulaconsole
  type: LoadBalancer
