# Create the actual deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulapropeller
  namespace: nebula
  labels:
    app: nebulapropeller
spec:
  selector:
    matchLabels:
      app: nebulapropeller
  template:
    metadata:
      labels:
        app: nebulapropeller
        app.kubernetes.io/name: nebulapropeller
        app.kubernetes.io/version: 0.7.1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 1001
        fsGroupChangePolicy: "Always"
      serviceAccountName: nebulapropeller
      volumes:
        - name: config-volume
          configMap:
            name: nebula-propeller-config
        - name: auth
          secret:
            secretName: nebula-secret-auth
      containers:
        - name: nebulapropeller
          image: nebulapropeller:v0.7.1
          command:
            - nebulapropeller
          args:
            - --config
            - /etc/nebula/config/*.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10254
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nebula/config
            - name: auth
              mountPath: /etc/secrets/
