# Create a ClusterRole for nebulapropeller
# https://kubernetes.io/docs/admin/authorization/rbac/
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebulapropeller
rules:
#Allow RO access to PODS
 - apiGroups:
    - ""
   resources:
    - pods
   verbs:
    - get
    - list
    - watch
#Allow Event recording access
 - apiGroups:
    - ""
   resources:
    - events
   verbs:
    - create
    - update
    - delete
    - patch
#Allow Access All plugin objects
 - apiGroups:
    - "*"
   resources:
    - "*"
   verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
#Allow Access to CRD
 - apiGroups:
   - apiextensions.k8s.io
   resources:
   - customresourcedefinitions
   verbs:
   - get
   - list
   - watch
   - create
   - delete
   - update
#Allow Access to all resources under nebula.lyft.com
 - apiGroups:
   - nebula.lyft.com
   resources:
   - nebulaworkflows
   - nebulaworkflows/finalizers
   verbs:
   - get
   - list
   - watch
   - create
   - update
   - delete
   - patch
   - post
   - deletecollection
---
# Create a Service Account for Nebulapropeller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebulapropeller
  namespace: nebula
---
# Create a binding from Role -> ServiceAccount
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebulapropeller
  namespace: nebula
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nebulapropeller
subjects:
- kind: ServiceAccount
  name: nebulapropeller
  namespace: nebula
