apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-pod-webhook
  namespace: nebula
  labels:
    app: nebula-pod-webhook
spec:
  selector:
    matchLabels:
      app: nebula-pod-webhook
  template:
    metadata:
      labels:
        app: nebula-pod-webhook
        app.kubernetes.io/name: nebula-pod-webhook
        app.kubernetes.io/version: 0.5.13
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 1001
        fsGroupChangePolicy: "Always"
      serviceAccountName: nebula-pod-webhook
      initContainers:
        - name: generate-secrets
          image: nebulapropeller:v0.5.13
          imagePullPolicy: IfNotPresent
          command:
            - nebulapropeller
          args:
            - webhook
            - init-certs
            - --config
            - /etc/nebula/config/*.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nebula/config
      containers:
        - name: webhook
          image: nebulapropeller:v0.5.13
          imagePullPolicy: IfNotPresent
          command:
            - nebulapropeller
          args:
            - webhook
            - --config
            - /etc/nebula/config/*.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nebula/config
              readOnly: true
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: nebula-propeller-config
        - name: webhook-certs
          secret:
            secretName: nebula-pod-webhook
