# Create a ClusterRole for the webhook
# https://kubernetes.io/docs/admin/authorization/rbac/
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebula-pod-webhook
  namespace: nebula
rules:
  - apiGroups:
      - "*"
    resources:
      - mutatingwebhookconfigurations
      - secrets
      - pods
      - replicasets/finalizers
    verbs:
      - get
      - create
      - update
      - patch
---
# Create a Service Account for webhook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebula-pod-webhook
  namespace: nebula
---
# Create a binding from Role -> ServiceAccount
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebula-pod-webhook
  namespace: nebula
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nebula-pod-webhook
subjects:
  - kind: ServiceAccount
    name: nebula-pod-webhook
    namespace: nebula
