{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nebula-binary.fullname" . }}-cluster-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "nebula-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.labels }}
    {{- tpl ( .Values.rbac.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- tpl ( .Values.rbac.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nebula-binary.rbac.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nebula-binary.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
