apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # All the resources that make up the deployment
  - nebula
  ########
  # Operators to be enabled
  #############
  # Dependencies to be configured
  # In local we use minio, but in cloud environment use S3 / GCS / AFS / Oracle Blob store etc
  # This is used for Resource pooling. On cloud you can use hosted redis (e.g. AWS elasticache)
  # Contour is used to create ingress. On cloud service use the default provided ingress controllers or cloud LB's
  # Add node ports for ease of use locally
  - ../../base/ingress
  - ../../base/addons/database
  - ../../base/addons/kubernetes_dashboard
  - ../../base/addons/storage
  - ../../base/addons/contour_ingress_controller

resources:
  - nodeport-services.yaml

# Images that should be used
images:
  # NebulaAdmin
  - name: nebulaadmin # match images with this name
    newTag: v1.1.118 # NEBULAADMIN_TAG override the tag
    newName: cr.nebula.org/nebulaclouds/nebulaadmin # override the name
  # NebulaConsole
  - name: nebulaconsole # match images with this name
    newTag: v1.9.2 # NEBULACONSOLE_TAG  the tag
    newName: cr.nebula.org/nebulaclouds/nebulaconsole # override the namep
  # Nebula DataCatalog
  - name: datacatalog # match images with this name
    newTag: v1.0.51 # DATACATALOG_TAG override the tag
    newName: cr.nebula.org/nebulaclouds/datacatalog # override the name
  # NebulaPropeller
  - name: nebulapropeller # match images with this name
    newTag: v1.1.116 # NEBULAPROPELLER_TAG override the tag
    newName: cr.nebula.org/nebulaclouds/nebulapropeller # override the name
  # Webhook
  - name: webhook # match images with this name
    newTag: v1.1.116 # NEBULAPROPELLER_TAG override the tag
    newName: cr.nebula.org/nebulaclouds/nebulapropeller # override the name
  # Override postgres image to use alpine based (rather smaller) docker image
  - name: postgres
    newTag: 13-21.04_beta
    newName: ecr.nebula.org/ubuntu/postgres
  - name: minio
    newTag: 2021.10.13-debian-10-r0
    newName: ecr.nebula.org/bitnami/minio
  - name: redis
    newTag: 6.2.5-debian-10-r59
    newName: ecr.nebula.org/bitnami/redis
