// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/nebulaclouds/nebula/nebulapropeller/pkg/apis/nebulaworkflow/v1alpha1"
	scheme "github.com/nebulaclouds/nebula/nebulapropeller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NebulaWorkflowsGetter has a method to return a NebulaWorkflowInterface.
// A group's client should implement this interface.
type NebulaWorkflowsGetter interface {
	NebulaWorkflows(namespace string) NebulaWorkflowInterface
}

// NebulaWorkflowInterface has methods to work with NebulaWorkflow resources.
type NebulaWorkflowInterface interface {
	Create(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.CreateOptions) (*v1alpha1.NebulaWorkflow, error)
	Update(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (*v1alpha1.NebulaWorkflow, error)
	UpdateStatus(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (*v1alpha1.NebulaWorkflow, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NebulaWorkflow, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NebulaWorkflowList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NebulaWorkflow, err error)
	NebulaWorkflowExpansion
}

// nebulaWorkflows implements NebulaWorkflowInterface
type nebulaWorkflows struct {
	client rest.Interface
	ns     string
}

// newNebulaWorkflows returns a NebulaWorkflows
func newNebulaWorkflows(c *NebulaworkflowV1alpha1Client, namespace string) *nebulaWorkflows {
	return &nebulaWorkflows{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nebulaWorkflow, and returns the corresponding nebulaWorkflow object, and an error if there is any.
func (c *nebulaWorkflows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	result = &v1alpha1.NebulaWorkflow{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NebulaWorkflows that match those selectors.
func (c *nebulaWorkflows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NebulaWorkflowList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NebulaWorkflowList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nebulaWorkflows.
func (c *nebulaWorkflows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nebulaWorkflow and creates it.  Returns the server's representation of the nebulaWorkflow, and an error, if there is any.
func (c *nebulaWorkflows) Create(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.CreateOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	result = &v1alpha1.NebulaWorkflow{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nebulaWorkflow).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nebulaWorkflow and updates it. Returns the server's representation of the nebulaWorkflow, and an error, if there is any.
func (c *nebulaWorkflows) Update(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	result = &v1alpha1.NebulaWorkflow{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		Name(nebulaWorkflow.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nebulaWorkflow).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nebulaWorkflows) UpdateStatus(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	result = &v1alpha1.NebulaWorkflow{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		Name(nebulaWorkflow.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nebulaWorkflow).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nebulaWorkflow and deletes it. Returns an error if one occurs.
func (c *nebulaWorkflows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nebulaWorkflows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nebulaworkflows").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nebulaWorkflow.
func (c *nebulaWorkflows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NebulaWorkflow, err error) {
	result = &v1alpha1.NebulaWorkflow{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nebulaworkflows").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
