{{- if .Values.nebulaconsole.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-console-config
  namespace: {{ template "nebula.namespace" . }}
  labels: {{ include "nebulaconsole.labels" . | nindent 4 }}
data: {{ toYaml .Values.configmap.console | nindent 2 }}
{{- end }}
