apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebula-binary.webhook.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "nebula-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
    {{- tpl ( .Values.service.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- tpl ( .Values.service.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.commonAnnotations }}
    {{- tpl ( .Values.service.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
  selector: {{- include "nebula-binary.selectorLabels" . | nindent 4 }}
