# ClusterRole for nebulaadmin
# https://kubernetes.io/docs/admin/authorization/rbac/
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebulaadmin
  namespace: nebula
rules:
#Allow Access to all resources under nebula.lyft.com and the core API group: ""
 - apiGroups:
   - ""
   - nebula.lyft.com
   - rbac.authorization.k8s.io
   resources:
   - configmaps
   - nebulaworkflows
   - namespaces
   - pods
   - resourcequotas
   - roles
   - rolebindings 
   - secrets
   - services
   - serviceaccounts
   - spark-role
   verbs:
   - "*"

---
# Create a Service Account for FltyeAdmin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebulaadmin
  namespace: nebula

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nebulaadmin-binding
  namespace: nebula
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nebulaadmin
subjects:
  - kind: ServiceAccount
    name: nebulaadmin
    namespace: nebula
