// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/nebulaclouds/nebula/nebulapropeller/pkg/apis/nebulaworkflow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNebulaWorkflows implements NebulaWorkflowInterface
type FakeNebulaWorkflows struct {
	Fake *FakeNebulaworkflowV1alpha1
	ns   string
}

var nebulaworkflowsResource = schema.GroupVersionResource{Group: "nebulaworkflow.nebula.net", Version: "v1alpha1", Resource: "nebulaworkflows"}

var nebulaworkflowsKind = schema.GroupVersionKind{Group: "nebulaworkflow.nebula.net", Version: "v1alpha1", Kind: "NebulaWorkflow"}

// Get takes name of the nebulaWorkflow, and returns the corresponding nebulaWorkflow object, and an error if there is any.
func (c *FakeNebulaWorkflows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nebulaworkflowsResource, c.ns, name), &v1alpha1.NebulaWorkflow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NebulaWorkflow), err
}

// List takes label and field selectors, and returns the list of NebulaWorkflows that match those selectors.
func (c *FakeNebulaWorkflows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NebulaWorkflowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nebulaworkflowsResource, nebulaworkflowsKind, c.ns, opts), &v1alpha1.NebulaWorkflowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NebulaWorkflowList{ListMeta: obj.(*v1alpha1.NebulaWorkflowList).ListMeta}
	for _, item := range obj.(*v1alpha1.NebulaWorkflowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nebulaWorkflows.
func (c *FakeNebulaWorkflows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nebulaworkflowsResource, c.ns, opts))

}

// Create takes the representation of a nebulaWorkflow and creates it.  Returns the server's representation of the nebulaWorkflow, and an error, if there is any.
func (c *FakeNebulaWorkflows) Create(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.CreateOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nebulaworkflowsResource, c.ns, nebulaWorkflow), &v1alpha1.NebulaWorkflow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NebulaWorkflow), err
}

// Update takes the representation of a nebulaWorkflow and updates it. Returns the server's representation of the nebulaWorkflow, and an error, if there is any.
func (c *FakeNebulaWorkflows) Update(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (result *v1alpha1.NebulaWorkflow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nebulaworkflowsResource, c.ns, nebulaWorkflow), &v1alpha1.NebulaWorkflow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NebulaWorkflow), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNebulaWorkflows) UpdateStatus(ctx context.Context, nebulaWorkflow *v1alpha1.NebulaWorkflow, opts v1.UpdateOptions) (*v1alpha1.NebulaWorkflow, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nebulaworkflowsResource, "status", c.ns, nebulaWorkflow), &v1alpha1.NebulaWorkflow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NebulaWorkflow), err
}

// Delete takes name of the nebulaWorkflow and deletes it. Returns an error if one occurs.
func (c *FakeNebulaWorkflows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nebulaworkflowsResource, c.ns, name), &v1alpha1.NebulaWorkflow{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNebulaWorkflows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nebulaworkflowsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NebulaWorkflowList{})
	return err
}

// Patch applies the patch and returns the patched nebulaWorkflow.
func (c *FakeNebulaWorkflows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NebulaWorkflow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nebulaworkflowsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NebulaWorkflow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NebulaWorkflow), err
}
