// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nebulaclouds/nebula/nebulapropeller/pkg/client/clientset/versioned/typed/nebulaworkflow/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNebulaworkflowV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNebulaworkflowV1alpha1) NebulaWorkflows(namespace string) v1alpha1.NebulaWorkflowInterface {
	return &FakeNebulaWorkflows{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNebulaworkflowV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
