apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-scheduler-config
  namespace: nebula
  labels:
    app.kubernetes.io/name: nebulascheduler
    app.kubernetes.io/instance: nebula
    helm.sh/chart: nebula-v0.1.10
    app.kubernetes.io/managed-by: Helm
data:
  admin.yaml: |
    admin:
      clientId: nebulapropeller
      clientSecretLocation: /etc/secrets/client_secret
      endpoint: nebulaadmin:81
      insecure: true
    event:
      capacity: 1000
      rate: 500
      type: admin
  db.yaml: |
    database:
      dbname: postgres
      host: postgres
      port: 5432
      username: postgres
  logger.yaml: |
    logger:
      level: 4
      show-source: true
