project_name: nebulacopilot
before:
  hooks:
    - go mod download
builds:
  - id: nebulacopilot
    env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      - -s -w -X github.com/nebulaclouds/nebulastdlib/version.Version={{.Version}} -X github.com/nebulaclouds/nebulastdlib/version.Build={{.ShortCommit}} -X github.com/nebulaclouds/nebulastdlib/version.BuildTime={{.Date}}
    binary: nebulacopilot
    goos:
      - linux
      - windows
      - darwin
archives:
  - id: nebulacopilot-archive
    name_template: |-
      nebulacopilot_{{ .Tag }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - nebulacopilot
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
