# Service
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  # use NodePort to make sure the service is accessible
  type: NodePort
  ports:
  - port: 80
    name: http
    protocol: TCP
    nodePort: 30081
