# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  commands:
    - cat monodocs-environment.lock.yaml
    - mamba install -c conda-forge conda-lock
    - conda-lock install -p /home/docs/monodocs-env monodocs-environment.lock.yaml
    - conda info
    - conda env list
    - cat docs/conf.py
    - cd docs && /home/docs/monodocs-env/bin/python -m sphinx -T -E -b html -d docs/_build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
