server:
  httpPort: 8088
  grpcPort: 8089
  security:
    # Controls whether to serve requests over SSL/TLS.
    secure: false
    # Controls whether to enforce authentication. Follow the guide in https://docs.nebula.org/ on how to setup authentication.
    useAuth: false
    allowCors: true
    allowedOrigins:
      # Accepting all domains for Sandbox installation
      - "*"
    allowedHeaders:
      - "Content-Type"
      - "nebula-authorization"
auth:
  authorizedUris:
    # This should point at your public http Uri.
    - https://localhost:30081
    # This will be used by internal services in the same namespace as nebulaadmin
    - http://nebulaadmin:80
    # This will be used by internal services in the same cluster but different namespaces
    - http://nebulaadmin.nebula.svc.cluster.local:80

  # Controls app authentication config
  appAuth:
    thirdPartyConfig:
      nebulaClient:
        clientId: nebulactl
        redirectUri: https://localhost:53593/callback
        scopes:
          - offline
          - all
  # Controls user authentication
  userAuth:
    openId:
      baseUrl: https://accounts.google.com
      scopes:
        - profile
        - openid
      clientId: 657465813211-6eog7ek7li5k7i7fvgv2921075063hpe.apps.googleusercontent.com
nebulaadmin:
  roleNameKey: "iam.amazonaws.com/role"
