resources:
- spark-operator.yaml
- sparkapplications-crd.yaml
- scheduledsparkapplications-crd.yaml
- deployment.yaml
- webhook.yaml

vars:
  - name: NAMESPACE
    objref:
      kind: Deployment
      name: sparkoperator
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.namespace
