apiVersion: batch/v1
kind: Job
metadata:
  name: sparkoperator-init
  namespace: sparkoperator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v2.4.5-v1beta2
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v2.4.5-v1beta2
    spec:
      serviceAccountName: sparkoperator
      restartPolicy: Never
      containers:
        - name: main
          image: gcr.io/spark-operator/spark-operator:v1beta2-1.1.2-2.4.5
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/gencerts.sh","--namespace", "$(NAMESPACE)", "-p"]
---
kind: Service
apiVersion: v1
metadata:
  name: spark-webhook
  namespace: sparkoperator
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: webhook
  selector:
    app.kubernetes.io/name: sparkoperator
